# config.yaml
---
inventory:
       plugin: SimpleInventory
       options:
            host_file: 'inventory\hosts.yaml'
            group_file: 'inventory\groups.yaml'
            defaults_file: 'inventory\default.yaml'
runner:
       plugin: threaded
       options:
            num_workers: 2
